export default function Terms() {
  return (
    <main className="max-w-2xl mx-auto py-12 px-4 sm:px-8 text-gray-900" style={{ fontFamily: 'Inter, Open Sans, ui-sans-serif, sans-serif' }}>
      <h1 className="text-3xl font-bold mb-6">Terms & Conditions</h1>
      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">Use of Service</h2>
        <p>AIrena is an AI productivity platform. Users must not use the platform for any illegal, harmful, or unauthorized activities. We reserve the right to suspend accounts found in violation of these terms.</p>
      </section>
      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">Account Responsibility</h2>
        <p>Users are responsible for maintaining the security of their login credentials. Please do not share your password with others. AIrena is not liable for any loss or damage resulting from unauthorized account access.</p>
      </section>
      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">Service Availability</h2>
        <p>We strive to provide high uptime and reliable service. However, occasional outages or maintenance may occur. We are not liable for any interruptions or loss of access.</p>
      </section>
      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">No Guarantees</h2>
        <p>Responses generated by AI are for informational purposes only. AIrena does not guarantee the accuracy, completeness, or suitability of any response. We are not liable for any decisions or losses resulting from the use of our services.</p>
      </section>
      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">Modification of Terms</h2>
        <p>We may update these terms from time to time. Continued use of the service implies acceptance of the updated terms. We recommend reviewing this page periodically.</p>
      </section>
      <section className="mb-6">
        <h2 className="text-xl font-semibold mb-2">Contact</h2>
        <p>For any questions regarding these terms, please email us at <a href="mailto:ramachandrasriharsha123@gmail.com" className="text-blue-600 underline">ramachandrasriharsha123@gmail.com</a>.</p>
      </section>
    </main>
  );
} 